name: Linting workflows

on:
  push:
    paths:
      - .github/**
    branches: 
      - main
  pull_request:
    paths:
      - .github/**

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: "Check GitHub workflow files"
        uses: docker://docker.mirror.hashicorp.services/rhysd/actionlint@sha256:3f24bf9d72ca67af6f9f8f3cc63b0e24621b57bf421cecfc452c3312e32b68cc # 1.6.24
        with:
          args: -color
