name: Linting workflows

on:
  push:
    paths:
      - .github/**
    branches: 
      - main
  pull_request:
    paths:
      - .github/**

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: "Check GitHub workflow files"
        uses: docker://docker.mirror.hashicorp.services/rhysd/actionlint@sha256:3f24bf9d72ca67af6f9f8f3cc63b0e24621b57bf421cecfc452c3312e32b68cc # 1.6.24
        with:
          args: -color
